- type: job
  id: StationRepresentative
  name: job-name-sr
  description: job-description-sr
  playTimeTracker: JobHeadOfPersonnel
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # Triad - 30 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # Triad - 5 hours
    - !type:RoleTimeRequirement
      role: JobSecurityGuard
      time: 18000 # Triad - 5 hours
    - !type:RoleTimeRequirement
      role: JobStc
      time: 18000 # Triad - 5 hours
  whitelisted: true
  startingGear: SrGear
  alwaysUseSpawner: true
  assignedCompany: Colonial
  icon: "JobIconHeadOfPersonnel"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  weight: 170
  displayWeight: 60 # Top
  canBeAntag: false
  accessGroups:
  - AllAccessSR
  ranks: # Triad, ranks
    RankOverseer: []
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ] # Triad - re-add sec implant
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: ShipSavingBlacklist # Triad - can't save ships
      - type: NpcFactionMember
        factions:
        - TDF # Triad - They aren't apart of the TDF, but they are friendly and work with them
      - type: CryoSleepRadioOverride
        overrides:
        - Nfsd # TDF radio
        - Service # Colonial Staff radio
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SrGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # Triad
  storage:
    back:
    - Flash
    - RubberStampSr
    - DoorRemoteCommand
    # - EncryptionKeyCentCom Triad
    - EncryptionKeyStationMasterSR #Mono start
    - EncryptionKeyDiplomacy
    - PhoneInstrumentHigh
