- type: job
  id: MdMedic
  name: job-name-md-medic
  description: job-description-md-medic
  playTimeTracker: MdMedic
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 27000 # 7.5 hours - Half by Triad
  startingGear: MdMedicGear
  alwaysUseSpawner: true
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-doc
  weight: 170
  displayWeight: 55 # Second from the top
  assignedCompany: MD
  canBeAntag: false
  accessGroups:
  - GeneralAccess
  - Medical
  ranks: # Triad, ranks
    RankEmergencyResponder: []
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ] # Triad - removed tracking implant
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
        - MD
      - type: SurgerySpeedModifier
        SpeedModifier: 1.75
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: MdMedicGear
  equipment:
    pocket1: HypoMini
    pocket2: MedicalAppraisalTool
  storage:
    back:
    - RubberStampDoctor
    - BoxFolderMedicalDoctor
