# FUCs->FMCs, value 5x normal frontier value

- type: entity
  name: Federation Military Credit # Mono - Renamed from FUCs
  parent: BaseItem
  id: FederationMilitaryCredit # Mono - Renamed from FUCs
  suffix: 100 FMC # Mono
  description: A token awarded to TSF personnel for turning in contraband. It can be exchanged in an TSFMC uplink device for a variety of law enforcement tools.
  components:
  - type: Sprite
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    state: frontieruplinkcoin
  - type: Item
    sprite: _NF/Objects/Specific/Security/frontieruplinkcoin.rsi
    size: Tiny
  - type: Stack
    count: 100 # Mono
    stackType: FederationMilitaryCredit
  - type: StaticPrice
    price: 0
  - type: StackPrice
    price: 40 # Mono
  - type: Currency
    price:
      FederationMilitaryCredit: 1

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit1
  suffix: 1 FMC
  components:
  - type: Stack
    count: 1

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit5
  suffix: 5 FMC
  components:
  - type: Stack
    count: 5

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit25
  suffix: 25 FMC
  components:
  - type: Stack
    count: 25

- type: entity
  parent: FederationMilitaryCredit
  id: FederationMilitaryCredit50
  suffix: 50 FMC
  components:
  - type: Stack
    count: 50
