using Content.Shared._Triad.Holosign;
using Content.Shared.Contests;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Triad.Holosign.UI;

[GenerateTypedNameReferences]
public sealed partial class HolosignProjectorLabelWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entManager = default!;

    public event Action<string>? OnDescriptionChanged;
    public event Action<bool>? OnExplicitChanged;

    private EntityUid? _owner;

    public HolosignProjectorLabelWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    private void Initialize()
    {
        if (_owner == null)
            return;

        if (!_entManager.HasComponent<LabelHolosignOnProjectedComponent>(_owner))
            return;

        Reload();

        DescriptionTextBox.OnTextChanged += args =>
        {
            var text = Rope.Collapse(args.TextRope).Trim();
            OnDescriptionChanged?.Invoke(text);
        };

        ExplicitBox.OnToggled += args =>
        {
            OnExplicitChanged?.Invoke(args.Pressed);
        };
    }

    public void SetOwner(EntityUid owner)
    {
        _owner = owner;

        Initialize();
    }

    public void Reload()
    {
        if (!_entManager.TryGetComponent<LabelHolosignOnProjectedComponent>(_owner, out var projectorLabel))
            return;

        if (!DescriptionTextBox.HasKeyboardFocus())
        {
            var rope = new Rope.Leaf(projectorLabel.Description);
            DescriptionTextBox.TextRope = rope;
        }

        ExplicitBox.Pressed = projectorLabel.Explicit;
    }
}
