- type: playTimeTracker
  id: JobTdfChiefEnforcer

- type: playTimeTracker
  id: JobTdfWarden

- type: playTimeTracker
  id: JobTdfPatrolTeamLeader

- type: playTimeTracker
  id: JobTdfMedic

- type: playTimeTracker
  id: JobTdfEnforcer

- type: playTimeTracker
  id: JobTdfCadet
